### ISSUE TITLE
ImportError: inpaint.so: invalid ELF header

### ISSUE THREAD

**Issue by nv-quan** [phulin/rebook#11]
I'm trying to run dewarp.py but this error happens. Do you happen to know that is the issue? 
By the way here is my python packages, could you please provide something similar so the installation could be done easier?
`appdirs==1.4.3
backports.functools-lru-cache==1.6.1
cloudpickle==1.3.0
configparser==4.0.2
contextlib2==0.6.0.post1
cycler==0.10.0
Cython==0.29.15
decorator==4.4.2
distlib==0.3.0
enum34==1.1.10
filelock==3.0.12
importlib-metadata==1.5.0
importlib-resources==1.0.2
kiwisolver==1.1.0
lxml==4.5.0
matplotlib==2.2.5
networkx==2.2
numpy==1.13.0
opencv-python==4.2.0.32
pathlib2==2.3.5
Pillow==6.2.2
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.0.3
rawpy==0.13.1
scandir==1.10.0
scikit-image==0.14.5
scipy==1.2.3
six==1.14.0
subprocess32==3.5.4
typing==3.7.4.1
virtualenv==20.0.7
zipp==1.2.0`
Thank you very much.

**Comment by phulin** [comment]
It's probably an issue with you Cython installation. Sorry, missed this issue when you posted it

**Comment by nv-quan** [comment]
Glad that you've added requirements.txt
